### ISSUE TITLE
build issu

### ISSUE THREAD

**Issue by master7720** [Sxmurai/inferno#44] opened 2021-09-22 12:33 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Unable to get mutable Windows environment variable map
idk what happen

**Comment by HausemasterIssue** [comment] 2021-09-22 12:40
look up how to build minecraft hack clients: https://www.youtube.com/watch?v=5dEgxdLUQoI and actually use google for once :)

**Comment by Sxmurai** [comment] 2021-09-22 12:42
not a bug, changed label

**Comment by Sxmurai** [comment] 2021-09-22 12:43
plus a quick google search should answer this:
https://stackoverflow.com/questions/67098755/build-failed-unable-to-get-mutable-windows-environment-variables

you just need to add JAVA_HOME

to be clear, i also dont reccomend using it as a main client because its still a bit buggy (rotations mostly)

**Comment by master7720** [comment] 2021-09-23 03:50
ah ok thanks

**Comment by HausemasterIssue** [comment] 2021-09-24 16:26
@Sxmurai close this

**Closed** 2021-09-25 02:15 UTC
Labels: question
